[![Ava Colabis](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/adlerpriit/2025_taka_fall/blob/main/teemad/python/Pandas.ipynb)

# Tabelandmed Pandasega

Pandas on Pythoni teek tabelandmete töötlemiseks. Siin õpid andmeid laadima ja kontrollima, ridu valima, uusi veerge arvutama ning rühmade kokkuvõtteid koostama.

**Eeldused:** oskad kasutada listi, sõnastikku, tingimust ja funktsiooni ning kasutada objekti meetodeid. Vajaduse korral korda [Intro](Intro.ipynb) põhiosa. Põhiosa hõlmab peatükke P1–P6; P7–P9 on valikuline lisamaterjal.

Näited ja harjutused kasutavad sama andmestikku. Näidete käivitamine ei sõltu harjutuste lahendamisest. Vaata [lahenduskäike](lahendused/Pandas_lahendused.md) pärast seda, kui oled ise proovinud.

<a id="p1"></a>
## P1. Andmete laadimine

Pandas on eraldi paigaldatav teek, mis ei kuulu Pythoni standardteeki. Kui kasutasid [alustamisjuhist](README.md), on see keskkonnas olemas. Colabis on Pandas tavaliselt juba paigaldatud.

`import pandas as pd` impordib Pandase ja annab sellele lühinime `pd`. Import ei paigalda teeki; pärast kerneli taaskäivitamist tuleb impordilahter uuesti käivitada. `from pathlib import Path` toob kasutusse standardteegi failitee klassi, mida ei pea eraldi paigaldama. Vajaduse korral korda [Intro peatükki I8](Intro.ipynb#i8).

`pd.read_csv()` on Pandase funktsioon, `algandmed.head()` aga andmetabeli meetod. Mõlemas on punkt, kuid esimeses pöördud teegi, teises konkreetse tabeli poole. `pd.read_csv()` loeb CSV-faili **DataFrame'iks** ehk andmetabeliks. CSV on tekstivorming tabelandmete hoidmiseks. Selles failis on esimesel real veerunimed ja järgmistel ridadel andmed; ühe rea väljad on eraldatud komadega.

Järgmine lahter otsib faili repo `data` kaustast. Kui kohalikku faili pole, loetakse sama andmestik kursuse repo veebiaadressilt. Lahter kuvab kasutatud failitee või veebiaadressi. Kui jätkad tööd pärast kerneli taaskäivitamist, käivita esmalt see lahter uuesti.

`display()` kuvab tabeli vormindatult. Ka lahtri viimane avaldis kuvatakse automaatselt; mitme tulemuse jaoks kasuta `display()` või `print()`.

Dokumentatsioon: [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).

In [1]:
# Teekide ja vajalike nimede importimine.
from pathlib import Path
import pandas as pd
from IPython.display import display

# Proovi esmalt repo juurkausta, seejärel töövihiku kausta suhtelist teed.
andmefail = Path("data/Islander_data.csv")
if not andmefail.is_file():
    andmefail = Path("../../data/Islander_data.csv")

if andmefail.is_file():
    allikas = andmefail
else:
    allikas = "https://raw.githubusercontent.com/adlerpriit/2025_taka_fall/37b50eb8474faeeb0993c2d4883680bee0560cbd/data/Islander_data.csv"

print("Andmete allikas:", allikas)
print("Pandase versioon:", pd.__version__)

# CSV lugemine Pandase tabeliks.
algandmed = pd.read_csv(allikas)
display(algandmed.head())

Andmete allikas: https://raw.githubusercontent.com/adlerpriit/2025_taka_fall/37b50eb8474faeeb0993c2d4883680bee0560cbd/data/Islander_data.csv
Pandase versioon: 2.2.3

,first_name,last_name,age,Happy_Sad_group,Dosage,Drug,Mem_Score_Before,Mem_Score_After,Diff
0,Bastian,Carrasco,25,H,1,A,63.5,61.2,-2.3
1,Evan,Carrasco,52,S,1,A,41.6,40.7,-0.9
2,Florencia,Carrasco,29,H,1,A,59.7,55.1,-4.6
3,Holly,Carrasco,50,S,1,A,51.7,51.2,-0.5
4,Justin,Carrasco,52,H,1,A,47.0,47.1,0.1

Andmestikus on virtuaalsete katseisikute mälukatse tulemused. Üks lähterida kirjeldab ühe katseisiku mõõtmisi enne ja pärast katset. `age` on vanus, `Drug` ravimirühm ja `Dosage` annusetase. `Happy_Sad_group` eristab rõõmsate (`H`) ja kurbade (`S`) mälestuste rühma.

`Diff = Mem_Score_After − Mem_Score_Before`. Positiivne väärtus tähendab **skoori suurenemist**, negatiivne vähenemist. See ei tähenda mõõdiku täpse selgituseta automaatselt mälu paranemist. Ravimikoodid on `A` alprasolaam, `T` triasolaam ja `S` platseebo.

Täielik [andmekirjeldus ja allikaviide](../../data/README.md) on repo andmekaustas. Hoia `algandmed` muutmata ning tee teisendused töökoopias.

<a id="p2"></a>
## P2. Tabel, veerg ja andmete kontroll

**DataFrame** on ridadest ja veergudest koosnev andmetabel. Kui valid tabelist ühe veeru kujul `inimesed["vanus"]`, saad **Series**-objekti: väärtuste jada koos reaindeksiga.

**Indeks** annab igale reale tähise, mille järgi saab seda valida. Järgmises näites loob Pandas indeksiks arvud 0, 1, 2 ja 3. Indeks ei pruugi aga olla rea järjekorranumber: selleks võib kasutada ka teksti või kuupäevi. Filtreerimisel jäävad alles valitud ridade senised indeksiväärtused.

Hoia reaindeksi väärtused ja veerunimed unikaalsed ehk kordumatud. Tehniliselt lubab Pandas mõlemas kordusi, kuid neid tasub vältida: need võivad muuta valiku tulemuse ootamatuks või põhjustada mõnes toimingus vea.

Alusta väikese tabeliga. Sõnastiku võtmetest saavad veerunimed ja listidest veergude väärtused. Kõigis listides peab olema sama palju elemente.

Dokumentatsioon: [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html), [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html).

In [2]:
# DataFrame: tabeli loomine sõnastikust.
inimesed = pd.DataFrame({
    "nimi": ["Mari", "Jaan", "Liis", "Peeter"],
    "vanus": [24, 38, 29, 46],
    "linn": ["Tartu", "Tallinn", "Tartu", "Pärnu"],
})
display(inimesed)

# Series: ühe veeru valimine tabelist.
display(inimesed["vanus"])

     nimi  vanus     linn
0    Mari     24    Tartu
1    Jaan     38  Tallinn
2    Liis     29    Tartu
3  Peeter     46    Pärnu

0    24
1    38
2    29
3    46
Name: vanus, dtype: int64

Andmetabeli uurimisel küsi kõigepealt: mida üks rida tähendab, millised veerud on olemas ning kas väärtused on sobivat tüüpi?

- `.head(n)` tagastab esimesed `n` rida. Nende kuvamiseks kasuta `display()` või jäta meetodikutse lahtri viimaseks avaldiseks.
- `.shape` annab enniku `(ridade arv, veergude arv)`. See on atribuut, mistõttu selle järele väljakutse sulge ei lisata.
- `.info()` näitab veergude tüüpe ja olemasolevate väärtuste arvu.
- `.describe()` annab siin arvuliste veergude statistilise kokkuvõtte.

Täisarve sisaldava veeru tüüp võib olla `int64`, ujukomaarve sisaldaval veerul `float64`. Tekstiveeru tüübinimi võib Pandase versioonist sõltuvalt olla `str`, `string` või `object`. Andmetüüp ei määra üksi tunnuse tähendust: arvuline annusetase võib analüüsis olla kategooria.

Dokumentatsioon: [head](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html), [shape](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html), [info](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html), [describe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html).

In [ ]:
# Atribuut shape: ridade ja veergude arv.
print("Ridu ja veerge:", inimesed.shape)

# Meetod info(): andmetüübid ja olemasolevate väärtuste arv.
inimesed.info()

# Meetod describe(): arvuliste veergude statistiline kokkuvõte.
display(inimesed.describe())

<a id="p-01"></a>

### Ülesanne P-01

Uuri tabelit `algandmed`: kuva esimesed kaheksa rida, ridade ja veergude arv ning iga veeru andmetüüp ja olemasolevate väärtuste arv. Nimeta kaks arvulist tunnust ning kaks tunnust, mida kasutaksid rühmade moodustamiseks.

**Enesekontroll:** faili päises on üheksa veergu. Kas oskad selgitada `Drug` ja `Dosage` tähendust?

In [23]:
algandmed.shape

(198, 9)

In [24]:
algandmed.info()
algandmed.head(8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   first_name        198 non-null    object
 1   last_name         198 non-null    object
 2   age               198 non-null    int64
 3   Happy_Sad_group   198 non-null    object
 4   Dosage            198 non-null    int64
 5   Drug              198 non-null    object
 6   Mem_Score_Before  198 non-null    float64
 7   Mem_Score_After   198 non-null    float64
 8   Diff              198 non-null    float64
dtypes: float64(3), int64(2), object(4)
memory usage: 14.1+ KB

,first_name,last_name,age,Happy_Sad_group,Dosage,Drug,Mem_Score_Before,Mem_Score_After,Diff
0,Bastian,Carrasco,25,H,1,A,63.5,61.2,-2.3
1,Evan,Carrasco,52,S,1,A,41.6,40.7,-0.9
2,Florencia,Carrasco,29,H,1,A,59.7,55.1,-4.6
3,Holly,Carrasco,50,S,1,A,51.7,51.2,-0.5
4,Justin,Carrasco,52,H,1,A,47.0,47.1,0.1
5,Liam,Carrasco,37,S,1,A,66.4,58.1,-8.3
6,Ava,Durand,35,S,1,A,44.1,56.0,11.9
7,Jamie,Durand,38,H,1,A,76.3,74.8,-1.5

Arvulised tunnused on age ja Dosage. Rühmade moodustamiseks kasutaksin Happy_Sad_group ja Drug.

<a id="p3"></a>
## P3. Valimine, filtreerimine ja sortimine

`tabel["veerg"]` valib ühe veeru ja tagastab Series-objekti. `tabel[["a", "b"]]` valib veerud `"a"` ja `"b"` ning tagastab neist koosneva tabeli. Sisemised nurksulud moodustavad veerunimede listi.

`.loc[read, veerud]` võimaldab valida korraga nii ridu kui ka veerge. Enne koma määra valitavad read indeksi tähiste või tingimusega; pärast koma anna veerunimi või veerunimede list.

Tingimus `inimesed["vanus"] >= 30` annab iga rea kohta väärtuse `True` või `False`. Kui kasutad seda tingimust ridade valimiseks, jäävad alles ainult `True`-ga märgitud read. Näites valime vähemalt 30-aastaste inimeste nimed ja linnad.

Dokumentatsioon: [loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html).

In [25]:
# Veergude valimine veerunimede listiga.
display(inimesed[["nimi", "vanus"]])

# Võrdlus: iga rea kohta saadakse True või False.
display(inimesed["vanus"] >= 30)

# loc: tingimusele vastavate ridade ja soovitud veergude valimine.
vahemalt_30 = inimesed.loc[inimesed["vanus"] >= 30, ["nimi", "linn"]]
display(vahemalt_30)

     nimi  vanus
0    Mari     24
1    Jaan     38
2    Liis     29
3  Peeter     46

0    False
1     True
2    False
3     True
Name: vanus, dtype: bool

     nimi     linn
1    Jaan  Tallinn
3  Peeter    Pärnu

Veergude võrdlemisel saadud tingimusi ühenda märkidega `&` (ja) ja `|` (või). Märk `~` pöörab tingimuse vastupidiseks. Pane iga võrdlus sulgudesse. Pythoni `and` ja `or` ei sobi tervete tõeväärtusveergude ühendamiseks.

`.sort_values()` järjestab read valitud veeru järgi. `ascending=False` annab kahaneva järjekorra. Järgmises näites tagastab meetod uue tabeli; algtabel jääb samaks.

Dokumentatsioon: [sort_values](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html).

In [26]:
# Filtreerimine: mõlemad tingimused peavad kehtima.
tartu_valik = inimesed.loc[
    (inimesed["linn"] == "Tartu") & (inimesed["vanus"] > 25),
    ["nimi", "vanus"],
]
display(tartu_valik)

# Sortimine: suurima muutusega read esimesena.
display(algandmed.sort_values("Diff", ascending=False).head(5))

   nimi  vanus
2  Liis     29

,first_name,last_name,age,Happy_Sad_group,Dosage,Drug,Mem_Score_Before,Mem_Score_After,Diff
48,Miki,Carrasco,35,H,3,A,65.0,114.0,49.0
56,Megan,Kennedy,27,S,3,A,81.0,120.0,39.0
60,Laura,McCarthy,34,S,3,A,57.3,96.0,38.7
54,Takahiro,Durand,53,S,3,A,54.8,88.2,33.4
63,Naoto,Steiner,39,H,3,A,61.6,88.5,26.9

<a id="p-02"></a>

### Ülesanne P-02

Koosta tabelist `algandmed` kaks eraldi valikut:

1. Osalejad, kelle vanus on üle 30 ja perekonnanimi `Durand`.
2. Osalejad ravimirühmast `A`, kelle annusetase on 3.

Kuva kummagi valiku ridade arv. Sorteeri teine valik `Diff` järgi kahanevalt.

**Vihje:** ridade arvu saad `len(tabel)` abil. **Enesekontroll:** kontrolli, et iga valitud rida vastab mõlemale tingimusele. Sorteeritud tabelis peab iga järgmine `Diff`-väärtus olema eelmisest väiksem või sellega võrdne.

In [40]:
durand_valik = algandmed.loc[
    (algandmed["last_name"] == "Durand") & (algandmed["age"] > 30),
    ["last_name", "age"],
]
display(len(durand_valik))

a_valik = algandmed.loc[
    (algandmed["Dosage"] == 3) & (algandmed["Drug"] == "A"),
    ["Dosage", "Drug"],
]
display(len(a_valik))

# Sortimine: suurima muutusega read esimesena.
display(algandmed.sort_values("Diff", ascending=False).head(5))

31

22

,first_name,last_name,age,Happy_Sad_group,Dosage,Drug,Mem_Score_Before,Mem_Score_After,Diff
48,Miki,Carrasco,35,H,3,A,65.0,114.0,49.0
56,Megan,Kennedy,27,S,3,A,81.0,120.0,39.0
60,Laura,McCarthy,34,S,3,A,57.3,96.0,38.7
54,Takahiro,Durand,53,S,3,A,54.8,88.2,33.4
63,Naoto,Steiner,39,H,3,A,61.6,88.5,26.9

*Kirjuta siia oma vastus või põhjendus.*

<a id="p4"></a>
## P4. Uus veerg ja puuduvad väärtused

`.copy()` loob tabelist koopia, mida saad muuta algtabelit muutmata. Uue veeru lisamiseks kirjuta omistamise vasakule poolele tabeli nimi ja nurksulgudesse uus veerunimi, näiteks `andmed["arvutatud_muutus"]`. Paremale poole kirjuta arvutus.

Kahe veeru lahutamisel leitakse siin iga rea jaoks pärast- ja enneskoori vahe. Eraldi Pythoni tsüklit pole vaja.

Dokumentatsioon: [copy](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html).

In [41]:
# Töökoopia loomine algandmeid muutmata.
andmed = algandmed.copy()

# Arvuline veerg: pärast- ja enneskoori vahe.
andmed["arvutatud_muutus"] = andmed["Mem_Score_After"] - andmed["Mem_Score_Before"]

# Tõeväärtusveerg: kas skoor suurenes?
andmed["skoor_suurenes"] = andmed["Diff"] > 0
display(andmed[["Mem_Score_Before", "Mem_Score_After", "Diff", "arvutatud_muutus", "skoor_suurenes"]].head())

   Mem_Score_Before  Mem_Score_After  Diff  arvutatud_muutus  skoor_suurenes
0              63.5             61.2  -2.3              -2.3           False
1              41.6             40.7  -0.9              -0.9           False
2              59.7             55.1  -4.6              -4.6           False
3              51.7             51.2  -0.5              -0.5           False
4              47.0             47.1   0.1               0.1            True

Puuduvate väärtuste loendamine koosneb kahest sammust:

1. `.isna()` annab iga tabeliväärtuse kohta tõeväärtuse: `True`, kui väärtus puudub, ja `False`, kui see on olemas.
2. Sellele järgnev `.sum()` liidab tõeväärtused igas veerus. `True` läheb arvesse ühena ja `False` nullina, seega saad iga veeru puuduvate väärtuste arvu.

Puuduv väärtus tähendab, et andmed on teadmata või sisestamata. See ei ole sama mis arv 0. Enne eemaldamist või täitmist selgita välja, millised read muutuksid ja kuidas see analüüsi mõjutab.

Allpool on eraldi näidistabel, kus üks vanus puudub. `.dropna(subset=["vanus"])` jätab kõrvale ainult puuduva vanusega read. Seda võib kasutada analüüsis, mis vajab teadaolevat vanust; arvesta, et osa kirjeid jääb siis analüüsist välja.

Dokumentatsioon: [isna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html), [sum](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html), [dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html).

In [42]:
# isna() märgib puuduvad väärtused; sum() loendab need veergude kaupa.
display(algandmed.isna().sum())

# Eraldi näidistabel, milles üks vanus puudub.
naide = pd.DataFrame({"nimi": ["Mari", "Jaan"], "vanus": [24, None]})
display(naide)

# dropna(): puuduva vanusega ridade väljajätmine.
display(naide.dropna(subset=["vanus"]))

first_name          0
last_name           0
age                 0
Happy_Sad_group     0
Dosage              0
Drug                0
Mem_Score_Before    0
Mem_Score_After     0
Diff                0
dtype: int64

   nimi  vanus
0  Mari   24.0
1  Jaan    NaN

   nimi  vanus
0  Mari   24.0

<a id="p-03"></a>

### Ülesanne P-03

Loo tabelist `algandmed` koopia. Lisa sellesse veerg `muutus_vahemalt_10`: väärtus on `True`, kui `Diff >= 10`, ja muul juhul `False`. Loenda tingimusele vastavad read. Kontrolli ka puuduvate `Diff`-väärtuste arvu.

**Vihje:** tõeväärtusveeru `.sum()` loendab `True`-väärtusi. **Enesekontroll:** kas kasutad õiget veerunime ja kas piirväärtus 10 on kaasatud? Selgita, miks `False` ei tähenda puuduvat väärtust.

In [43]:
andmed = algandmed.copy()
andmed["muutus_vahemalt_10"] = andmed["Diff"] >= 10
display(andmed["muutus_vahemalt_10"].sum())

print(andmed["Diff"].isna().sum())

np.int64(36)

0

*Kirjuta siia oma vastus või põhjendus.*

<a id="p5"></a>
## P5. Rühmade kokkuvõte

`groupby("Drug")` koondab sama ravimikoodiga read ühte rühma. Sellele järgnev `.agg()` arvutab iga rühma kohta soovitud kokkuvõtted.

Kirjes `keskmine_muutus=("Diff", "mean")` on `keskmine_muutus` loodava veeru nimi. Sulgudes olev ennik määrab, millisest veerust väärtused võtta (`"Diff"`) ja milline arvutus teha (`"mean"` ehk keskmine).

- `mean` arvutab keskmise ja `median` mediaani. Puuduvad väärtused jäetakse neist arvutustest välja.
- `size` loendab kõik rühma read.
- `count` loendab valitud veeru olemasolevad väärtused. Puuduva väärtusega rida selle arvu sisse ei lähe.

Lisa keskmise kõrvale nii ridade arv kui ka kasutatud väärtuste arv. Nii näed rühma suurust ja seda, kui paljude väärtuste põhjal keskmine arvutati.

Dokumentatsioon: [groupby](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html), [agg](https://pandas.pydata.org/docs/reference/api/pandas.api.typing.DataFrameGroupBy.agg.html), [size](https://pandas.pydata.org/docs/reference/api/pandas.api.typing.DataFrameGroupBy.size.html), [count](https://pandas.pydata.org/docs/reference/api/pandas.api.typing.DataFrameGroupBy.count.html).

In [44]:
# groupby() ja agg(): rühmade kokkuvõtted.
kokkuvote = algandmed.groupby("Drug").agg(
    keskmine_muutus=("Diff", "mean"),
    mediaan=("Diff", "median"),
    ridu=("Diff", "size"),
    skooriga_ridu=("Diff", "count"),
).reset_index()  # Rühmitamistunnus tagasi tavaliseks veeruks.

# round(): ümardatud tulemuse kuvamine algset kokkuvõtet muutmata.
display(kokkuvote.round(2))

  Drug  keskmine_muutus  mediaan  ridu  skooriga_ridu
0    A             9.47      7.9    67             67
1    S            -0.17      0.3    66             66
2    T            -0.59      0.2    65             65

Pärast rühmitamist on ravimikood kokkuvõttetabeli indeksis. `.reset_index()` teeb sellest tavalise veeru `Drug` ning loob uue reaindeksi alates nullist.

`.round(2)` tagastab tabeli, mille arvväärtused on ümardatud kahe komakohani. Näites kuvame selle tulemuse; muutujas `kokkuvote` säilivad ümardamata väärtused.

Siin annavad `size` ja `count` sama tulemuse, sest veerus `Diff` pole puuduvaid väärtusi. Allolevas väikeses näites erinevad need arvud.

Dokumentatsioon: [reset_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html), [round](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html).

In [45]:
# Näidistabel: rühmas A on üks skoor puudu.
puuduvusega = pd.DataFrame({"ruhm": ["A", "A", "B"], "skoor": [5, None, 8]})

# size loendab kõik read; count ainult olemasolevad skoorid.
display(puuduvusega.groupby("ruhm").agg(ridu=("skoor", "size"), skooriga_ridu=("skoor", "count")))

      ridu  skooriga_ridu
ruhm
A        2              1
B        1              1

### Rühmade läbimine for-tsükliga

`groupby()` tagastab `GroupBy`-objekti, mida saad läbida `for`-tsükliga. Igal sammul saad kaks väärtust:

- `ravimikood` on rühma võti, siin veeru `Drug` väärtus;
- `ruhma_tabel` on selle rühma kõiki ridu ja algseid veerge sisaldav `DataFrame`.

Näites kuvame iga ravimirühma suuruse ja kaks suurima skoorimuutusega kirjet. Sortimine ja ridade valimine toimuvad iga rühma sees eraldi.

`sort_values()` argument `key` määrab funktsiooni, mida rakendatakse veerule enne järjestamist. Siin kasutab `key=abs` absoluutväärtusi; tabelis säilivad algsed märgiga väärtused.

Tsükkel sobib siis, kui tahad iga rühmaga teha mitu toimingut, näiteks uurida selle ridu, koostada graafiku või salvestada eraldi faili. Tavalise kokkuvõttetabeli, näiteks rühmade keskmiste ja suuruste leidmiseks kasuta `.agg()`-i.

Dokumentatsioon: [rühmade läbimine](https://pandas.pydata.org/docs/user_guide/groupby.html#iterating-through-groups), [sort_values ja key](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html).

In [46]:
# Rühmade läbimine: igal sammul rühma võti ja sellele vastav alamtabel.
for ravimikood, ruhma_tabel in algandmed.groupby("Drug"):
    print(f"Ravimirühm {ravimikood}: {len(ruhma_tabel)} kirjet")

    # Selle rühma kahe absoluutväärtuselt suurima muutuse valimine.
    suurimad = ruhma_tabel.sort_values("Diff", key=abs, ascending=False).head(2)
    display(suurimad[["Mem_Score_Before", "Mem_Score_After", "Diff"]])

Ravimirühm A: 67 kirjet

    Mem_Score_Before  Mem_Score_After  Diff
48              65.0            114.0  49.0
56              81.0            120.0  39.0

Ravimirühm S: 66 kirjet

     Mem_Score_Before  Mem_Score_After  Diff
109              84.5             44.1 -40.4
83               74.0             90.0  16.0

Ravimirühm T: 65 kirjet

     Mem_Score_Before  Mem_Score_After  Diff
168              33.4             57.5  24.1
188             110.0             87.8 -22.2

<a id="p-04"></a>

### Ülesanne P-04

Rühmita `algandmed` annusetaseme (`Dosage`) järgi. Leia iga rühma keskmine `Diff` ja ridade arv. Millise rühma keskmine on suurim? Mida üks kokkuvõttetabeli rida tähistab?

**Enesekontroll:** kui liidad kokku iga rühma ridade arvu, pead saama algtabeli ridade arvu. Põhjenda, miks see tabel üksi ei tõesta annuse põhjuslikku mõju.

In [49]:
kokkuvote = algandmed.groupby("Dosage").agg(
    keskmine_muutus=("Diff", "mean"),
    ridu=("Diff", "size"),
)

display(kokkuvote)

print(kokkuvote["keskmine_muutus"].idxmax())

print(kokkuvote["ridu"].sum())
print(len(algandmed))

        keskmine_muutus  ridu
Dosage
1              0.480597    67
2              2.092424    66
3              6.380000    65

3
198
198



```
# This is formatted as code
```

Suurim keskmine Dosage 3. Üks kokkuvottetabeli rida tähistab ühte doosiliiki.

<a id="p6"></a>
## P6. Tulemuse salvestamine

Salvesta kokkuvõte CSV-faili. `index=False` jätab Pandase reaindeksi failist välja, nii et CSV-sse lähevad ainult tabeli veerud. Sama nimega faili salvestamine kirjutab varasema sisu üle. Loe fail pärast salvestamist uuesti sisse ja kontrolli selle sisu.

Dokumentatsioon: [to_csv](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html).

In [50]:
# Failitee koostamine ja kausta loomine.
kaust = Path("valjund")
kaust.mkdir(exist_ok=True)
fail = kaust / "ravimiruhmade_kokkuvote.csv"

# CSV salvestamine ilma Pandase reaindeksita.
kokkuvote.to_csv(fail, index=False)
print("Salvestatud:", fail.resolve())

# Salvestatud faili uuesti lugemine sisu kontrollimiseks.
display(pd.read_csv(fail))

Salvestatud: /content/valjund/ravimiruhmade_kokkuvote.csv

   keskmine_muutus  ridu
0         0.480597    67
1         2.092424    66
2         6.380000    65

<a id="p-05"></a>

### Ülesanne P-05

Vasta tekstilahtris:

1. Mille poolest erinevad `.shape` ja `.head()`?
2. Millal annavad `size` ja `count` eri tulemuse?
3. Miks on filtris `(algandmed["age"] > 30) & (algandmed["Drug"] == "A")` mõlemad tingimused sulgudes?

**Enesekontroll:** leia iga vastuse juurde sobiv näide põhiosast.

1. .shape näitab ridade ja veergude arvu, head() aga ülemist x arvu ridu

2. count loendab ainult siis kui väärtus on olemas, seega kui mõnes kohas pole siis size loendab seda, aga count mitte

3. et mõlemaid arvesse võtaks, et hinnataks ära sulgudes olev enne seda kui &-iga tegevust tehakse
---

Põhiosa on läbitud. Edasi liigu [Seaborni vihikusse](Seaborn.ipynb). Vajaduse korral võrdle oma vastuseid [lahenduskäikudega](lahendused/Pandas_lahendused.md).

Järgmised peatükid on lisamaterjal. Nende läbimine ei ole Seaborni vihiku põhiosa ega lõpuülesande eelduseks.

<a id="p7"></a>
## P7. Lisamaterjal: tabelite liitmine

`merge()` ühendab tabeleid ühise veeru ehk võtme väärtuste järgi. Näites lisame igale ravimikoodile ravimi nimetuse. `on="Drug"` määrab, et vasted leitakse veeru `Drug` järgi.

Kutses `algandmed.merge(ravimid, ...)` on vasakpoolne tabel `algandmed` ja parempoolne `ravimid`. `how="left"` jätab alles kõik vasakpoolse tabeli read, ka need, millele parempoolsest tabelist vastet ei leita. Sel juhul jääb lisatud raviminimetus puudu.

`validate="many_to_one"` kontrollib, et parempoolses tabelis esineb iga võtme väärtus ainult üks kord. Vasakpoolses tabelis võib sama ravimikood korduda. Kui parempoolses tabelis oleks sama kood mitmel real, võiks ühendamine suurendada tulemuse ridade arvu.

Salvesta tulemus uude muutujasse, et `algandmed` säiliks. Pärast ühendamist kontrolli ridade arvu ja seda, kas kõik raviminimetused on olemas. `.notna()` annab olemasoleva väärtuse korral `True`; sellele järgnev `.all()` kontrollib, kas kõik saadud tõeväärtused on `True`.

Dokumentatsioon: [merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html).

In [ ]:
# Vastavustabel: ravimikood ja nimetus.
ravimid = pd.DataFrame({
    "Drug": ["A", "T", "S"],
    "ravim": ["Alprasolaam", "Triasolaam", "Platseebo"],
})

# merge(): nimetuste ühendamine andmetega ravimikoodi järgi.
nimedega = algandmed.merge(ravimid, on="Drug", how="left", validate="many_to_one")

# Ühendamise kontroll: ridade arv säilis ja kõik nimetused leiti.
assert len(nimedega) == len(algandmed)
assert nimedega["ravim"].notna().all()
display(nimedega.head())

<a id="p-l1"></a>
<a id="p-l01"></a>

### Lisaülesanne P-L01

Loo vastavustabel, kus koodile `H` vastab nimetus `"Rõõmsad"` ja koodile `S` nimetus `"Kurvad"`. Ühenda see tabeliga `algandmed` veeru `Happy_Sad_group` järgi, nii et nimetused lisanduvad veergu `malestused`. Salvesta tulemus uude muutujasse ja jäta `algandmed` muutmata.

**Enesekontroll:** tulemuses on sama palju ridu kui algtabelis ja veerus `malestused` pole puuduvaid väärtusi. Tabelisse `algandmed` ei ole uut veergu lisandunud.

In [ ]:
# Kirjuta siia oma kood. Vajaduse korral lisa lahtreid.

*Kirjuta siia oma vastus või põhjendus.*

`concat()` ühendab tabeleid ridade või veergude kaupa. Ridade kaupa ühendamine sobib sama struktuuriga tabelitele. Veergude kaupa ühendamisel pannakse kõrvuti sama **indeksiväärtusega** read; määrav ei ole nende asukoht tabelis.

`.iloc[]` valib ridu ja veerge nende asukoha järgi, loendades nullist. Näiteks `.iloc[:2]` valib esimesed kaks rida, olenemata nende indeksiväärtustest.

Näites jagame tabeli kaheks ja ühendame osad uuesti. `ignore_index=True` loob ühendatud tabelile uue reaindeksi alates nullist.

Dokumentatsioon: [concat](https://pandas.pydata.org/docs/reference/api/pandas.concat.html), [iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html).

In [ ]:
# iloc: tabeli jagamine ridade asukoha järgi.
algus = algandmed.iloc[:2]
lopp = algandmed.iloc[2:]

# concat(): osade ühendamine ridade kaupa uue reaindeksiga.
taastatud = pd.concat([algus, lopp], ignore_index=True)

# Kontroll: ühendamise tulemus vastab algtabelile.
assert taastatud.equals(algandmed)
print("Taastatud ridu:", len(taastatud))

<a id="p8"></a>
## P8. Lisamaterjal: lai ja pikk tabel

**Laias tabelis** on ühe katseisiku skoorid enne ja pärast katset sama rea eri veergudes: `Mem_Score_Before` ja `Mem_Score_After`.

**Pikas tabelis** on iga mõõtmine eraldi real. Veerg `skoor` sisaldab mõõdetud väärtust ja veerg `mootmine` näitab, kas see pärineb enne- või pärastmõõtmisest. Seega saab algtabeli ühest reast kaks rida. `.melt()` teeb selle teisenduse.

Enne teisendamist lisame töökoopiasse veeru `rea_id`, mis annab igale algtabeli reale kordumatu numbri. Selle järgi saad pärast teisendust kokku viia samalt algtabeli realt pärit mõõtmised. Katseisikute nimed korduvad, seega ei sobi nimi siin rea tuvastamiseks.

- `id_vars` loetleb veerud, mis jäävad mõlema mõõtmise juurde alles: siin `rea_id`, `Drug` ja `Dosage`.
- `value_vars` loetleb mõõtmisi sisaldavad veerud, mille väärtused lähevad ühte veergu.
- `var_name="mootmine"` annab nime veerule, kuhu lähevad algsed mõõtmisveergude nimed.
- `value_name="skoor"` annab nime veerule, kuhu lähevad skoorid.

Kontrollis rühmitame tulemuse `rea_id` järgi. `.size()` loendab iga rühma read, `.eq(2)` kontrollib, kas neid on kaks, ja `.all()` kontrollib, kas see kehtib kõigis rühmades.

Dokumentatsioon: [melt](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.melt.html).

In [ ]:
# Algsete ridade tähistamine enne tabeli teisendamist.
lai = algandmed.copy()
lai["rea_id"] = range(len(lai))

# melt(): kahe mõõtmisveeru teisendamine eraldi ridadeks.
pikk = lai.melt(
    id_vars=["rea_id", "Drug", "Dosage"],
    value_vars=["Mem_Score_Before", "Mem_Score_After"],
    var_name="mootmine",
    value_name="skoor",
)
display(pikk.head())
print("Ridu:", len(pikk))

# Kontroll: iga algse rea kohta on kaks mõõtmist.
assert pikk.groupby("rea_id").size().eq(2).all()

### Tabeli kuju muutmine pivot() abil

`pivot()` muudab ainult tabeli kuju. Iga rea- ja veerutunnuse kombinatsiooni kohta peab lähtetabelis olema kõige rohkem üks rida. Kui sama kombinatsioon kordub, kasuta kokkuvõtte arvutamiseks `pivot_table()`-it.

Järgmises näites muudame eelmise näite pika tabeli `pikk` tagasi laiaks. `index="rea_id"` määrab tulemuse read, `columns="mootmine"` veerud ja `values="skoor"` lahtritesse paigutatavad väärtused. Iga algse rea kohta on pikas tabelis üks enne- ja üks pärastmõõtmine. Seetõttu vastab igale `rea_id` ja `mootmine` kombinatsioonile üks skoor.

Tulemuses on enne- ja pärastmõõtmise skoorid jälle kõrvuti. Nende väärtused ei muutu ning keskmisi ei arvutata. Siin taastame ainult skooriveerud; `Drug` ja `Dosage` jäävad tulemusest välja.

Dokumentatsioon: [pivot](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html).

In [ ]:
# pivot(): enne- ja pärastmõõtmise skoorid tagasi eri veergudesse.
skoorid_laias_tabelis = pikk.pivot(
    index="rea_id", columns="mootmine", values="skoor"
)
display(skoorid_laias_tabelis.head())

### Risttabeli koostamine pivot_table() abil

`pivot_table()` arvutab kokkuvõtte ja paigutab tulemused risttabelisse. Järgmises näites kasutame tabelit `algandmed`: ridadesse tulevad ravimirühmad (`index="Drug"`) ja veergudesse annusetasemed (`columns="Dosage"`). Igas lahtris on selle ravimirühma ja annusetaseme keskmine `Diff` (`values="Diff", aggfunc="mean"`).

Sama ravimirühma ja annusetaseme kohta on algandmetes mitu kirjet. `pivot()` annaks nende andmetega vea, sest ühte tulemuse lahtrisse peaks minema mitu väärtust. `pivot_table()` arvutab siin nendest väärtustest keskmise.

Dokumentatsioon: [pivot_table](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot_table.html).

In [ ]:
# pivot_table(): keskmine muutus ravimirühma ja annusetaseme kaupa.
risttabel = algandmed.pivot_table(
    index="Drug", columns="Dosage", values="Diff", aggfunc="mean", observed=True
)

# Tulemuse ümardamine kuvamiseks.
display(risttabel.round(2))

<a id="p-l2"></a>
<a id="p-l02"></a>

### Lisaülesanne P-L02

Loo tabelist `algandmed` koopia ja lisa igale reale kordumatu tunnus `rea_id`. Teisenda tabel pikale kujule: pane enne- ja pärastmõõtmise väärtused veergu `skoor` ning nende algsed veerunimed veergu `mootmine`. Säilita iga mõõtmise juures ka `rea_id` ja `Happy_Sad_group`. Kontrolli, et igale `rea_id` väärtusele vastab kaks rida: üks enne- ja teine pärastmõõtmise jaoks.

**Enesekontroll:** ridade arv kahekordistub. `Diff` ei ole kolmas ajahetk ja seda mõõtmiste hulka ei lisata.

In [ ]:
# Kirjuta siia oma kood. Vajaduse korral lisa lahtreid.

*Kirjuta siia oma vastus või põhjendus.*

<a id="p9"></a>
## P9. Lisamaterjal: vanuserühmad ja töötlusahel

`pd.cut()` määrab iga arvväärtuse etteantud piiride järgi rühma. `bins` määrab vahemike piirid ja `labels` rühmade nimetused.

Näites kuuluvad esimesse rühma vanused 0–35, teise üle 35 kuni 50, kolmandasse üle 50 kuni 65 ning viimasesse üle 65. `right=True` kaasab igasse vahemikku ülemise piiri; `include_lowest=True` kaasab esimesse vahemikku ka alumise piiri 0. `float("inf")` tähistab lõpmatust, nii et viimasel rühmal ei ole lõplikku ülempiiri.

Rühmade nimetused peavad vastama nende piiridele. Sildid `"36–50"`, `"51–65"` ja `"66+"` sobivad siin, sest vanused on täisaastates.

Dokumentatsioon: [cut](https://pandas.pydata.org/docs/reference/api/pandas.cut.html).

In [ ]:
# cut(): vanuste jagamine nimetatud rühmadesse.
vanustega = algandmed.copy()
vanustega["vanuseruhm"] = pd.cut(
    vanustega["age"],
    bins=[0, 35, 50, 65, float("inf")],
    labels=["kuni 35", "36–50", "51–65", "66+"],
    right=True,
    include_lowest=True,
)

# value_counts(): kirjete arvu leidmine igas vanuserühmas.
display(vanustega["vanuseruhm"].value_counts(sort=False))

# Kontroll: iga vanus sai rühma.
assert vanustega["vanuseruhm"].notna().all()

<a id="p-l3"></a>
<a id="p-l03"></a>

### Lisaülesanne P-L03

Kontrolli sama vanuserühmade jaotust väärtustega `[24, 35, 36, 50, 51, 65, 66, 83]`. Põhjenda, millisesse rühma kuuluvad 35 ja 36.

**Enesekontroll:** igale kontrollitud vanusele peab vastama rühm; vanus 24 peab kuuluma rühma `"kuni 35"`.

In [ ]:
# Kirjuta siia oma kood. Vajaduse korral lisa lahtreid.

*Kirjuta siia oma vastus või põhjendus.*

### Mitmest sammust koosnev töötlusahel

Töötlusahelas kasutab iga samm eelmise sammu tulemust. Tabeli meetodeid saad kutsuda järjest; `.pipe()` võimaldab lisada ahelasse ka eraldi funktsiooni.

Näites leiame **ravimirühmade keskmise skoori muutuse vähemalt 30-aastaste katseisikute seas** ja sordime tulemuse kahanevalt. Skoori muutus on algandmete veerus `Diff`.

Kirjutame funktsiooni `ruhmade_kokkuvote`, mis leiab iga rühma keskmise ja kirjete arvu. Rühmitamisveeru ja arvulise veeru nimed antakse argumentidena, seega saab sama funktsiooni kasutada ka teiste veergude või tabelitega. Mõlemad veerud peavad sisendtabelis olemas olema.

In [ ]:
# Kasutaja kirjutatud funktsioon: veerunimed antakse argumentidena.
def ruhmade_kokkuvote(tabel, ruhma_veerg, arvuline_veerg):
    return (
        tabel.groupby(ruhma_veerg)
        .agg(keskmine=(arvuline_veerg, "mean"), ridu=(arvuline_veerg, "size"))
        .reset_index()
    )

`.query()` valib tingimusele vastavad read; tingimus kirjutatakse siin tekstina. `.sort_values()` sordib tulemuse. Mõlemad on tabeli meetodid, mida kasutame ahelas otse.

`.pipe()` annab eelmise sammu tabeli funktsiooni `ruhmade_kokkuvote` esimeseks argumendiks ning edastab ka veerunimed. Funktsiooni nimi kirjutatakse ilma väljakutse sulgudeta: selle kutsub välja `.pipe()`. Iga sammu jaoks ei ole vaja oma funktsiooni kirjutada; `.pipe()`-ile sobib ka olemasolev teegifunktsioon.

Ahelat ümbritsevad sulud lubavad kirjutada iga sammu eraldi reale.

Dokumentatsioon: [query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html), [pipe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html).

In [ ]:
ahela_kokkuvote = (
    algandmed
    # 1. Tabeli meetod: vali vähemalt 30-aastased katseisikud.
    .query("age >= 30")
    # 2. pipe(): anna valitud read ja veerunimed meie kokkuvõttefunktsioonile.
    .pipe(ruhmade_kokkuvote, ruhma_veerg="Drug", arvuline_veerg="Diff")
    # 3. Tabeli meetod: sordi rühmad keskmise muutuse järgi kahanevalt.
    .sort_values("keskmine", ascending=False)
)
display(ahela_kokkuvote.round(2))

## Edasi lugemiseks

- [Pandase algõpetus](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html) — otsi sama töötlussammu kohta teine näide.
- [DataFrame'i teatmik](https://pandas.pydata.org/docs/reference/frame.html) — meetodite parameetrid.

Kontrolli dokumentatsiooni versiooni. Oma versiooni näed `pd.__version__` kaudu.